version: '2'
services:
  sns:
    image: jameskbride/local-sns:dev
    ports:
    - "9911:9911"
    volumes:
    - ./config/db.json:/etc/sns/db.json
    - ./config/logs:/tmp/logs
    - ./config/output:/tmp/output
    environment:
      - DB_OUTPUT_PATH=/tmp/output/db.json
    depends_on:
    - sqs
  sqs:
    image: softwaremill/elasticmq-native:1.6.5
    ports:
    - "9324:9324"
    volumes:
    - ./config/elasticmq.conf:/opt/elasticmq.conf

