name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Prepare test environment
        run: |
          # Clean up any existing test database files
          rm -f testDb.json tmp/testDb.json tmp/test-db.json
          # Ensure tmp directory exists for test outputs
          mkdir -p tmp

      - name: Build with Gradle
        run: ./gradlew build
