name: CI/CD for local-sns Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test with Gradle
        run: ./gradlew build

      - name: Docker Setup
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io
          docker --version

      - name: Build Docker Image
        run: |
          make build-image
        working-directory: ./

#      - name: List Docker Images
#        run: docker images
#
#      - name: Push Docker Image to Container Registry
#        run: |
#          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#          docker tag your-docker-image-name:latest ${{ secrets.DOCKER_REGISTRY_URL }}/your-docker-image-name:latest
#          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/your-docker-image-name:latest

