name: CI/CD for local-sns Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Prepare test environment
        run: |
          # Clean up any existing test database files
          rm -f testDb.json tmp/testDb.json tmp/test-db.json
          # Ensure tmp directory exists for test outputs
          mkdir -p tmp

      - name: Build and Test with Gradle
        run: ./gradlew build
