name: CI/CD for local-sns Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test with Gradle
        run: ./gradlew build
